#######################################################################
# Key Bindings

# Set leader key
unbind-key C-b
set-option -g prefix C-r
bind-key C-r send-prefix

# Set pane navigation to vim keys
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Set pane splits
bind-key % split-window -h -c "#{pane_current_path}"
bind-key '"' split-window -c "#{pane_current_path}"

# Set client navigation
bind-key n switch-client -n
bind-key p switch-client -p

# Set up mouse functionality and vi navigation keys
setw -g mode-keys vi
setw -g mouse on

# Allow proper color rendering when using k9s/lazygit/etc... in tmux session
set -g default-terminal "xterm-256color"

#######################################################################
# Plugins
set-option -g @plugin 'tmux-plugins/tpm'
set-option -g @plugin 'christoomey/vim-tmux-navigator'
set-option -g @plugin 'erikw/tmux-powerline'

#######################################################################
# Initialize TMUX plugin manager 
# (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
